name: Deploy to Prod cluster

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gitlab
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.UNIQUE_GITLAB_TOKEN }} -F ref=master -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[DEPLOY_TO]=prod https://gitlab.uniquenetwork.dev/api/v4/projects/60/trigger/pipeline
